spring:
  datasource:
    url: jdbc:h2:file:./data/toledo-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
  sql:
    init:
      mode: always
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  mvc.pathmatch.matching-strategy: ant_path_matcher